// packages/react-cytoscape/src/App.tsx
import { useState, useEffect } from "react";
import "./App.css";

import { graphData } from "./data";
//const graphData = {nodes: {}};
import { useCytoscape } from "./cytoscape";

import { GraphAI } from "graphai";
import { streamMockAgent } from "@graphai/vanilla";

function App() {
  const [selectedGraph, __setSelectedGraph] = useState(graphData);
  const { cytoscapeRef, updateCytoscape } = useCytoscape(selectedGraph);

  const run = async () => {
    const graphai = new GraphAI(selectedGraph, { streamMockAgent });
    graphai.onLogCallback = async ({ nodeId, state }) => {
      // logs.value.push({ nodeId, state, inputs, result, errorMessage });
      updateCytoscape(nodeId, state);
      console.log(nodeId, state);
    };
    await graphai.run();
  };

  useEffect(() => {
    run();
  }, []);

  return (
    <>
      <div className="ext-3xl font-bold underline w-screen h-screen">
        <div ref={cytoscapeRef} className="w-full h-full" />
      </div>
    </>
  );
}

export default App;

// packages/vue-cytoscope/src/App.vue
<template>
<main>
  
  <div class="h-screen w-full">
    <div class="w-10/12 h-1/2 bg-white rounded-md mt-4 mx-auto border-2">
      <div ref="cytoscopeRef" class="w-full h-full" />
    </div>
    <div>
      a
    </div>
  </div>
</main>
</template>

<script lang="ts">
import { defineComponent, ref, computed, ComputedRef } from "vue";

import { GraphAI } from "graphai";
import { streamMockAgent } from "@graphai/vanilla";

import { graphData } from "./data";

import { useCytoscope } from "./composables/cytoscope";

export default defineComponent({
  setup() {
    const selectdGraph = ref(graphData)
    const { updateCytoscope, cytoscopeRef, resetCytoscope } = useCytoscope(selectdGraph);
    
    const run = async () => {
      const graphai = new GraphAI(graphData, { streamMockAgent });
      graphai.onLogCallback = async ({ nodeId, state, inputs, result, errorMessage }) => {
        // logs.value.push({ nodeId, state, inputs, result, errorMessage });
        updateCytoscope(nodeId, state);
        console.log(nodeId, state);
      };
      const results = await graphai.run();
    }
    run();

    return {
      cytoscopeRef
    };
  }
});
</script>


<style scoped>
header {
    line-height: 1.5;
}

.logo {
  display: block;
  margin: 0 auto 2rem;
}

@media (min-width: 1024px) {
  header {
    display: flex;
    place-items: center;
    padding-right: calc(var(--section-gap) / 2);
  }

  .logo {
    margin: 0 2rem 0 0;
  }

  header .wrapper {
    display: flex;
    place-items: flex-start;
    flex-wrap: wrap;
  }
}
</style>
